fuzzybee/fuzzybee/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fuzzybee.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'joboard.views.index',name='home'),
    url(r'^board/', include('joboard.urls', namespace="board")),
    url(r'^resume/', include('resume.urls', namespace="resume")),
    url(r'^people/', include('people.urls', namespace="people")),
    url(r'^admin/', include(admin.site.urls)),
)

fuzzybee/people/urls.py
from django.conf.urls import patterns,url
from people import views

urlpatterns = patterns('',
	# url(r'^$', views.IndexView.as_view(), name='index'),
	# url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	# url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),

	url(r'^signup/$', views.signup_view, name='signup'),
	url(r'^login/$', views.login_view, name="login"),
	url(r'^add_avatar/$', views.add_avatar, name="add_avatar"),
	url(r'^get_avatar/$', views.get_avatar, name="get_avatar"),

)

fuzzybee/people/models.py
from django.db import models
from django.contrib.auth.models import User
from utils.constant import GENDER

class People(models.Model):
    user = models.OneToOneField(User)
    nickname = models.CharField(max_length=24, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER)
    avatar = models.ImageField(upload_to='avatar')
    reserved = models.CharField(max_length=140)

    def avatar_url(self):
        """
        Returns the URL of the image associated with this Object.
        If an image hasn't been uploaded yet, it returns a stock image

        :returns: str -- the image url

        """
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        else:
            return 'default'

fuzzybee/people/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class SignupForm(ModelForm):
    class Meta:
        model = User
        fields = ['username','password']
        labels = {
            'username': _(u'用户名/手机号码'),
            'password': _(u'密码'),
        }

class LoginForm(forms.Form):

    username = forms.CharField(
        label=_("Username"),
        max_length=30,
        widget=forms.TextInput(),
        required=True
    )
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(render_value=False)
    )

fuzzybee/people/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render_to_response, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from people.models import People
from people.forms import SignupForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.template import RequestContext
import logging
logger = logging.getLogger(__name__)

def signup_view(request):
    form = None
    if request.method == 'POST':
        form = SignupForm(request.POST)
        print form
        if form.is_valid():
            signup = form.cleaned_data
            logger.debug("name: " + signup['username'])
            logger.debug("password: " + signup['password'])
            #save in user model
            user_model = form.save(commit=False)
            user_model.set_password(signup['password'])
            user_model.save()
            #save in people model
            people_model = People(user=user_model)
            people_model.save()

            return HttpResponseRedirect(reverse('people:login'))
    else:
        form = SignupForm()
    return render_to_response('people/signup.html', {'form': form}, context_instance=RequestContext(request))

def login_view(request):
    form = None
    if request.method == 'POST':
        form = LoginForm(request.POST)
        #print form
        if form.is_valid():

            username = request.POST.get('username', '')
            password = request.POST.get('password', '')

            print "name: " + username
            print "password: " + password

            user = authenticate(username=username,password=password)

            if user is not None:
                if user.is_active:
                    print "user active"
                    login(request, user)
                    return HttpResponseRedirect(reverse('board:manager'))
                else:
                    print "user not active"
                    return HttpResponse(404)
            else:
                print "user not exist"
                return HttpResponse(503)

    else:
        form = LoginForm()
    return render_to_response('people/login.html', {'form': form}, context_instance=RequestContext(request))

def logout_view(request):
    pass
    
def add_avatar(request):
    pass

def get_avatar(request):
    pass

fuzzybee/people/templates/people/login.html
{% extends "base/base.html" %}
{% block extrastyle %}
  {% load static %}
  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'css/signin.css' %}" />
  <link href="signin.css" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="container">

    <form class="form-signin" action="{% url 'people:login' %}" method="post">
      {% csrf_token %}
      <h2 class="form-signin-heading">Please login in</h2>
      {% for field in form.visible_fields %}
        {{field.label_tag}} {{ field }}
      {% endfor %}
      <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
      <a href="{% url 'people:signup'  %}">新用户注册</a>
    </form>

  </div> <!-- /container -->
{% endblock %}

fuzzybee/people/templates/people/signup.html
{% extends "base/base.html" %}
{% block extrastyle %}
  {% load static %}
  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'css/signin.css' %}" />
{% endblock %}

{% block content %}
  <div class="container">

    <form class="form-signin" action="{% url 'people:signup' %}" method="post">
      {% csrf_token %}
      <h2 class="form-signin-heading">Please sign in</h2>
      {% for field in form.visible_fields %}
        {{field.label_tag}} {{ field }}
      {% endfor %}
      <div class="checkbox">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>

  </div> <!-- /container -->
{% endblock %}