fuzzybee/fuzzybee/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fuzzybee.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'joboard.views.index',name='home'),
    url(r'^board/', include('joboard.urls', namespace="board")),
    url(r'^resume/', include('resume.urls', namespace="resume")),
    url(r'^people/', include('people.urls', namespace="people")),
    url(r'^admin/', include(admin.site.urls)),
)

fuzzybee/people/urls.py
from django.conf.urls import patterns,url
from people import views

urlpatterns = patterns('',
	# url(r'^$', views.IndexView.as_view(), name='index'),
	# url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	# url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),

	url(r'^signup/$', views.signup_view, name='signup'),
	url(r'^login/$', views.login_view, name="login"),
	url(r'^add_avatar/$', views.add_avatar, name="add_avatar"),
	url(r'^get_avatar/$', views.get_avatar, name="get_avatar"),

)

fuzzybee/resume/urls.py
from django.conf.urls import patterns, url
from resume import views

urlpatterns = patterns('',
    url(r'^applysync$', views.applysync, name='applysync'),
    url(r'^applylist$', views.applylist, name='applylist'),
    url(r'^applyid/(?P<fact_id>[0-9]+)$', views.applyid, name='applyid'),
)

fuzzybee/templates/base/base.html
{% load staticfiles %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<title>两个小蜜蜂</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<script language="JavaScript" async type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

{% block extrastyle %}
{% endblock %}

<div class="container">
  <!-- Static navbar -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">小蜜蜂</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'home' %}">招聘</a></li>
          <li><a href="#">关于</a></li>
          <li><a href="#">联系我们</a></li>
          <li><a href="{% url 'resume:applylist' %}">查看列表</a></li>
          <li><a href="{% url 'people:login' %}">登录/注册</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>
  {% block content %}
  {% endblock %}
</div><!-- /.container -->